spring:
  application:
    name: concurrency-lab # 建議兩邊標籤一致，用 instance 去拆分，或者你喜歡分開叫也行
  r2dbc:
    # 指向 docker-compose 裡的 db 服務
    url: r2dbc:postgresql://db:5432/lab_db
    username: user
    password: password
    pool:
      initial-size: 5
      max-size: 5 # 關鍵！故意設小，模擬高負載下的連線競爭
      max-create-connection-time: 2s

# 監控設定保持不變，這部分你已經改得很完美了
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  metrics:
    tags:
      application: ${spring.application.name}