spring:
  config:
    activate:
      on-profile: cloudrun

  cloud:
    gcp:
      project-id: notification-system-lab
      sql:
        instance-connection-name: ${CLOUD_SQL_INSTANCE}
        database-name: lab_db

  r2dbc:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 2
      max-size: 5
      max-create-connection-time: 2s

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

management:
  tracing:
    enabled: false
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

server:
  port: 8080
