services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  lab-flux:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODULE_NAME: lab-webflux  # <--- 確認這裡沒有拼錯
    container_name: lab-flux-container
    ports:
      - "8082:8082"
      - "5005:5005" # 讓 IntelliJ 也能從外面連進來
    networks:
      - monitoring-net

  # MVC 服務 (新增這個)
  lab-mvc:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODULE_NAME: lab-mvc     # 傳給 Dockerfile 的變數
    container_name: lab-mvc-container
    ports:
      - "8081:8081"
      - "5006:5005" # 為了避免衝突，Debug 埠號映射到主機的 5006
    networks:
      - monitoring-net
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
    volumes:
      - ./grafana_data:/var/lib/grafana  # 將面板存到本地資料夾

networks:
  monitoring-net:
    driver: bridge