services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab_db
    ports:
      - "5432:5432"
    networks:
      - monitoring-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      # 簡化指令，只要能連上就算數
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user}" ]
      interval: 3s
      timeout: 3s
      retries: 5

  lab-flux:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODULE_NAME: lab-webflux
    container_name: lab-flux-container
    ports:
      - "8082:8082"
      - "5005:5005"
    networks:
      - monitoring-net
    environment:
      # 1. 暴力破解 8080 問題：直接在環境變數指定 Port
      - SERVER_PORT=8082
      - SERVER_ADDRESS=0.0.0.0
      # 2. 資料庫連線資訊
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/lab_db
      - SPRING_R2DBC_USERNAME=user
      - SPRING_R2DBC_PASSWORD=password
      # 3. 解決 Alpine DNS 卡頓與 IPv4 優先
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
    depends_on:
      db:
        condition: service_healthy # <--- 這是關鍵！確保 DB 真的 Ready 才開始初始化連線池

  # MVC 服務 (新增這個)
  lab-mvc:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        MODULE_NAME: lab-mvc     # 傳給 Dockerfile 的變數
    container_name: lab-mvc-container
    ports:
      - "8081:8081"
      - "5006:5005" # 為了避免衝突，Debug 埠號映射到主機的 5006
    networks:
      - monitoring-net
    environment:
      # 1. 強制覆蓋資料庫 URL，確保它抓到的是 db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lab_db
      # 2. 解決 Alpine/Java DNS 解析問題，強制使用 IPv4
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
    depends_on:
      db:
        condition: service_healthy # 確保 DB 真的活了才開始連

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
    volumes:
      - grafana_data:/var/lib/grafana  # 將面板存到本地資料夾

  redis:
    image: redis:7.2-alpine
    container_name: redis-lab
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis
    command: redis-server --appendonly yes
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge

volumes:
  pgdata:          # 冒號後面留白代表使用預設設定 (Default Driver)
  grafana_data:    # 如果你也想永久保存 Grafana 面板，可以順便加上這個
  redis_data: