global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'java-concurrency-lab'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: 
          - 'lab-flux:8082'
          - 'lab-mvc:8081'
        labels:
          application: 'concurrency-lab'